#include "fs.h"

// ...existing code...

void kernel_main(void) {
    // ...existing code...
    int fs_status = fs_init();
    // Optionally handle fs_status for debugging
    // ...existing code...
}

// ...existing code...